'''
    This file contains functions for printing result of tests into a output.txt file
    Also functions that parses input schedule in input.txt into a 4D array so we can 
    run tests on it
'''
def write_output_header(file):
    file.write("This report is generated by the Anderson, if there is any bugs or suggestions please contact him.\n")

def write_output_game_list(file, game_list, description):
    # game_list is a array of True/False
    file.write("\n")
    file.write(description)
    file.write("\n")
    for game_index,game in enumerate(game_list):
        file.write("Game " + str(game_index+1) + " : " + str(game) + "\n")

def write_output_team_dict(file, team_dict, description):
    # team_dict is a disctionary of items
    file.write("\n")
    file.write(description)
    file.write("\n")
    for team_index in range(len(team_dict)):
        file.write("Team " + str(team_index+1) + " : " + str(team_dict[team_index]) + "\n")

def write_output_2d_array(file, two_d_array, description):
    file.write("\n")
    file.write(description)
    file.write("\n")
    file.write(format_2d_array(two_d_array))
    file.write("\n")


def format_2d_array(two_d_array):
    # reference : https://stackoverflow.com/a/17871279
    first_row = "\t" + ''.join(['T{}\t'.format(i) for i in range(len(two_d_array))]) + "\n"
    return first_row + '\n'.join([''.join(['T' + str(row_index+1)] + ['\t{}'.format(item) for item in row]) for row_index,row in enumerate(two_d_array)])
