'''
    This file contains functions for printing result of tests into a output.txt file
    Also functions that parses input schedule in input.txt into a 4D array so we can 
    run tests on it
'''
def write_output_header(file):
    file.write("This report is generated by the Anderson, if there is any bugs or suggestions please contact him.\n")

def write_output_game_list(file, game_list, description):
    # game_list is a array of True/False
    file.write("\n")
    file.write(description)
    for game_index,game in enumerate(game_list):
        file.write("Game " + str(game_index+1) + " : " + str(game) + "\n")